---
title: "Pilot2 Vigour data analysis"
author: "Haoyang"
date: today
date-format: full
format: 
    html:
        toc: true
        embed-resources: true
editor: visual
editor_options: 
  chunk_output_type: inline
---

## Load .csv data, exported from Julia

```{r}
library(here)
library(tidyverse)
theme_set(theme_minimal())
raw_data <- read_csv(here("data", "pilot2_vigour_data.csv"))

```

## Processing data, particularly reaction times

```{r}
theme_set(theme_minimal())
data <- raw_data %>%
    mutate(
        response_times = str_extract_all(response_times, "\\d+"),
        response_times = map(response_times, as.numeric)
    )
```

## Missed trials

```{r}
data %>% 
    group_by(prolific_id) %>% 
    summarize(n_miss = sum(trial_presses == 0)) %>% 
    ggplot(aes(x = n_miss)) +
    geom_histogram() +
    scale_y_continuous(breaks = seq(0, 40, by = 5))

many_misses <- data %>% 
    group_by(prolific_id) %>% 
    summarize(n_miss = sum(trial_presses == 0)) %>% arrange(desc(n_miss)) %>% filter(n_miss > 0)

```

```{r}
#| message: false
data %>% 
    filter(trial_presses == 0) %>% 
    ggplot(aes(x = reward_per_press)) +
    stat_count(geom = "point") +
    stat_count(geom = "line") +
    facet_wrap(~ prolific_id, labeller = labeller(prolific_id = ~ str_sub(.x, -5, -1))) +
    labs(x = "Reward/press", y = "# Missing trials")

```

## Number of key presses

### By reward magnitudes

```{r}
data %>% 
    # filter(trial_presses != 0) %>% 
    group_by(prolific_id, ratio, magnitude) %>% 
    summarize(trial_presses = mean(trial_presses)) %>% 
    ungroup() %>% 
    ggplot(aes(x = magnitude, y = trial_presses)) +
    # geom_point(alpha = 0.1) +
    # geom_smooth(aes(group = prolific_id), method = "lm", se = F, linewidth = 0.3) +
    geom_hline(aes(yintercept = ratio), linetype = "dotted", color = "black") +
    geom_line(aes(group = prolific_id), linewidth = 0.15, color = "royalblue", alpha = 0.25) +
    stat_summary(fun = mean, geom = "line") +
    facet_wrap(~ ratio)
```

```{r}
data %>% 
    # filter(trial_presses != 0) %>% 
    group_by(prolific_id, ratio) %>% 
    summarize(trial_presses = mean(trial_presses)) %>% 
    ungroup() %>% 
    ggplot(aes(x = ratio, y = trial_presses)) +
    # geom_point(alpha = 0.1) +
    # geom_smooth(se = F, linewidth = 0.3, method = "lm") +
    geom_line(aes(group = prolific_id), linewidth = 0.15, color = "royalblue", alpha = 0.25) +
    stat_summary(fun.data = mean_se) +
    geom_abline(slope = 2, intercept = 0, linetype = "dotted", color = "black") +
    geom_abline(slope = 1, intercept = 0, linetype = "dotted", color = "black")
```

```{r}
p_rpp <- data %>% 
    # filter(trial_presses != 0) %>% 
    ggplot(aes(x = reward_per_press, y = trial_presses)) +
    stat_summary(aes(group = prolific_id), fun = mean, geom = "line", linewidth = 0.15, color = "gray50", alpha = 0.25) +
    stat_summary(fun = mean, geom = "line", color = "#4065f6") +
    labs(x = "Reward/press", y = "Trial presses", caption = "Blue line: group average")
```

```{r pilot2_presses_by_trial_rpp_and_conditions}
#| fig-height: 8
#| fig-width: 8

library(patchwork)
p_trial <- data %>%
  ggplot(aes(x = trial_number, y = trial_presses)) +
  stat_summary(
    aes(y = ratio),
    fun = mean,
    geom = "line",
    color = "darkorange",
    linewidth = 0.5,
    linetype = "dotted"
  ) +
  geom_line(
    aes(group = prolific_id),
    alpha = 0.25,
    linewidth = 0.15,
    color = "gray50"
  ) +
  stat_summary(fun = mean,
               geom = "line",
               color = "#4065f6") +
  geom_blank() +
  labs(x = "Trial number", y = "Trial presses",
       caption = str_wrap("Solid blue line: group average; Dotted orange line: fixed ratio", 80))

p_fr_mag <- data %>%
  # filter(trial_presses != 0) %>%
  group_by(prolific_id, ratio, magnitude) %>%
  summarize(trial_presses = mean(trial_presses)) %>%
  ungroup() %>%
  ggplot(aes(x = ratio, y = trial_presses)) +
  geom_hline(
    aes(yintercept = magnitude),
    color = "purple",
    linetype = "dashed",
    linewidth = 0.5
  ) +
  geom_line(
    aes(group = prolific_id),
    alpha = 0.25,
    linewidth = 0.15,
    color = "gray50"
  ) +
  stat_summary(fun = mean,
               geom = "line",
               color = "#4065f6") +
  facet_grid( ~ magnitude, labeller = label_both) +
  labs(x = "Fixed ratio", y = "Trial presses", caption = "Blue line: group average; Purple line: magnitude level in pence")

p_rpp/p_trial/p_fr_mag + plot_annotation(tag_levels = "A")
```

## Response times

```{r}
data %>% 
    filter(trial_presses != 0) %>% 
    filter(trial_number > 4) %>% 
    anti_join(many_misses) %>% 
    mutate(first_rt = map_dbl(response_times, 1),
           typical_rt = map2_dbl(response_times, ratio, ~ mean(.x[seq_along(.x) %% .y != 1], na.rm = T)),
           after_coin_rt = map2_dbl(response_times, ratio, ~ mean(.x[seq_along(.x) %% (.y + 1) == 0]))) %>% 
    group_by(prolific_id, reward_per_press, magnitude) %>% 
    summarize(across(c(first_rt, typical_rt, after_coin_rt), ~ mean(.x, na.rm = T))) %>% 
    ungroup() %>% 
    ggplot(aes(x = reward_per_press, y = typical_rt)) +
    geom_line(aes(group = prolific_id), color = "#4065f6", linewidth = 0.15, alpha = 0.25) +
    stat_summary(fun = ~ median(.x, na.rm = T), geom = "line") +
    facet_wrap(~ magnitude)
```

```{r}
#| message: false
data %>%
    filter(trial_presses != 0) %>%
    filter(trial_number > 4) %>%
    anti_join(many_misses) %>%
    mutate(
        first_rt = map_dbl(response_times, 1),
        typical_rt_mean = map2_dbl(response_times, ratio, ~ mean(.x[seq_along(.x) %% .y != 1], na.rm = T)),
        after_coin_rt = map2_dbl(response_times, ratio, ~ mean(.x[seq_along(.x) %% (.y + 1) == 0]))
    ) %>%
    group_by(prolific_id) %>%
    summarize(across(
        c(first_rt, typical_rt_mean, after_coin_rt),
        ~ mean(.x, na.rm = T)
    )) %>%
    ungroup() %>% 
    pivot_longer(-prolific_id, names_to = "type", values_to = "rt") %>%
    ggplot(aes(x = type, y = rt)) + 
    geom_line(aes(group = prolific_id),
              color = "#4065f6",
              linewidth = 0.15, alpha = 0.25) + 
    stat_summary(fun.data = median_hilow)
```
