# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [optional-scope, feat, fix, docs, style, refactor, perf, test, chore, build, ci]

  - repo: local
    hooks:
      - id: validate-core-versions
        name: Validate core script versions
        entry: julia check_versions.jl
        language: system
        files: ^core/.*\.jl$
        pass_filenames: false
