---
title: "Analyses for Pilot 4"
author: "Haoyang"
date: last-modified
date-format: full
format: 
    html:
        toc: true
        embed-resources: true
editor: visual
editor_options: 
  chunk_output_type: inline
---

## Pavlovian transfer

```{r}
library(tidyverse)
library(afex)
library(emmeans)
library(here)
set_sum_contrasts()
theme_set(theme_minimal())

```

```{r}
pit_data <- read_csv(here("data", "pit_data.csv"))

```

### Instrumental effect

```{r}
pit_cont_mixed <- pit_data %>% 
    mutate(across(c(coin, reward_per_press), ~ as.vector(scale(.)))) %>% 
    mixed(press_per_sec ~ reward_per_press * coin + (reward_per_press * coin | prolific_id), data = .)

pit_cat_aov <- pit_data %>% 
    mutate(across(c(coin, reward_per_press), as.factor)) %>% 
    aov_4(press_per_sec ~ reward_per_press * coin + (reward_per_press * coin | prolific_id), data = ., fun_aggregate = mean)

pit_cat_mixed <- pit_data %>% 
    mutate(across(c(coin, reward_per_press), as.factor)) %>% 
    mixed(press_per_sec ~ reward_per_press * coin + (reward_per_press + coin | prolific_id), data = ., method = "S")

```

```{r}
pit_data %>% 
    group_by(prolific_id, reward_per_press) %>% 
    summarize(press_per_sec = mean(press_per_sec)) %>% 
    ggplot(aes(x = reward_per_press, y = press_per_sec)) +
    # geom_smooth(data = pit_data, method = "lm", formula = y ~ poly(x, 2)) +
    stat_summary(fun = mean, geom = "point") +
    stat_summary(fun = mean, geom = "line")

```

```{r}
emmeans(pit_cat_aov, pairwise ~ reward_per_press)
afex_plot(pit_cat_aov, x = "reward_per_press", error = "within")

```

### Pavlovian (transfer) effect

```{r}
afex_plot(pit_cat_aov, x = "coin", panel = "reward_per_press", error = "within", data_plot = F)

```

```{r}
pit_data %>% 
    group_by(prolific_id, coin) %>% 
    summarize(press_per_sec = mean(press_per_sec)) %>% 
    ggplot(aes(x = coin, y = press_per_sec)) +
    # geom_smooth(data = pit_data, method = "lm") +
    stat_summary(fun = mean, geom = "point") +
    stat_summary(fun = mean, geom = "line")
```

```{r}
emmeans(pit_cat_aov, pairwise ~ coin)
afex_plot(pit_cat_aov, x = "coin", error = "within")

```

```{r}
emmeans(pit_cat_aov, ~ coin) %>% 
    contrast(list(approach_avoid = c(-1/3, -1/3, -1/3, 1/3, 1/3, 1/3)))
```

```{r}
emmeans(pit_cat_mixed, ~ coin + reward_per_press, lmer.df = "asymptotic") %>% 
    joint_tests(by = "reward_per_press")
```

```{r}
afex_plot(pit_cat_mixed, x = "coin", panel = "reward_per_press", error = "within", data_plot = F)

```

```{r}
pit_trial_fit <- lm(press_per_sec ~ poly(trial_number, 2), pit_data)
pit_data <- add_column(pit_data, press_per_sec_resid = resid(pit_trial_fit))

pit_cat_mixed2 <- pit_data %>% 
    mutate(across(c(coin, reward_per_press), as.factor)) %>% 
    mixed(press_per_sec_resid ~ reward_per_press * coin + (reward_per_press + coin | prolific_id), data = ., method = "S")

```

```{r}
afex_plot(pit_cat_mixed2, x = "coin", panel = "reward_per_press", error = "within", data_plot = F)
```
