name: Sync Main to Vigour

on:
  push:
    branches:
      - main

jobs:
  sync-main-to-vigour:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4     
        with: 
          fetch-depth: 0 

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check commit origin and message
        id: check-origin
        run: |
          # Get the latest commit hash and message
          LATEST_COMMIT=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Check if commit message contains "from huyslab/vigour"
          if echo "$COMMIT_MSG" | grep -q "from huyslab/vigour"; then
            echo "Commit message indicates changes from vigour branch, skipping sync"
            echo "skip_sync=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check if this commit exists in vigour branch
          git fetch origin vigour
          if git merge-base --is-ancestor $LATEST_COMMIT origin/vigour; then
            echo "Changes originated from vigour branch, skipping sync"
            echo "skip_sync=true" >> $GITHUB_OUTPUT
          else
            echo "Changes did not originate from vigour, proceeding with sync"
            echo "skip_sync=false" >> $GITHUB_OUTPUT
          fi

      - name: Push changes to vigour
        if: |
          github.ref == 'refs/heads/main' && 
          steps.check-origin.outputs.skip_sync == 'false'
        run: |
          git fetch origin 
          git checkout vigour
          git merge main --no-edit
          git push origin vigour
